export default {
    accept: 'تایید',
    login: 'ورود',
    remember_username_password: 'مرا به خاطر بسپار',
    password: 'گذرواژه',

    hello: 'Hello',
    signup: 'ثبت نام',
    verification_code: 'کد تایید',
    first_name: 'نام',
    last_name: 'نام خانوادگی',
    username: 'نام کاربری',
    email: 'ایمیل',
    name_pull: 'نام نظر سنجی',
    name_first_team: 'نام  تیم اول',
    name_second_team: 'نام  تیم دوم',
    description: 'توضیحات',
    start_poll_date: ' تاریخ شروع نظر سنجی',
    end_poll_date: ' تاریخ پایان نظر سنجی',
    start_poll_time: ' زمان شروع نظر سنجی',
    end_poll_time: ' زمان پایان نظر سنجی',
    league_name: 'نام لیگ ',
    game_points: 'امتیاز بازی',
    enter_game_points: 'امتیاز بازی را وارد نمایید',
    enter_pull_name: 'نام نظر سنجی را وارد نمایید',
    enter_first_team_name: 'نام تیم اول را وارد نمایید',
    enter_description_name: 'توضیحات را وارد نمایید',
    enter_second_team_name: 'نام تیم دوم را وارد نمایید',
    enter_stadium_name: 'نام ورزشگاه را وارد نمایید',
    enter_league_name: 'نام لیگ را وارد نمایید',
    enter_user_name: 'نام کاربری را وارد نمایید',
    enter_password: 'رمز عبور را وارد نمایید',
    and: ' و',

    please_enter_your_mobile_and_password:
        'لطفا شماره همراه و کلمه عبور خود را وارد نمایید',
    please_enter_your_verification_code: 'لطفا کد ارسال شده  را وارد نمایید',

    please_enter_your_sign_up_field: 'لطفا ثبت نام کنید',
    please_enter_your_mobile_number: 'لطفا شماره موبایل خود را وارد نمایید',
    please_enter_your_mobile_number_correctly:
        'لطفا شماره همراه خود را به درستی وارد نمایید',
    please_enter_this_field: 'لطفا این فیلد را وارد نمایید',
    mobile_number: 'تلفن همراه',
    email_is_incorrect: 'فرمت ایمیل وارد شده صحیح نمی باشد',
    welcome_to_this_app: 'به برنامه خوش آمدید!',
    sign_up_not_yet: 'هنوز ثبت نام نکرده اید؟!',
    register: ' ثبت نام کنید',
    internet_connection_problem: 'لطفا اتصال اینترنت خود را بازبینی فرمایید',
    connection_problem: 'ارتباط با سرور دچار مشکل شده است',
    internal_server_error: 'سرور دچار مشکل شده است',
    username_password_incorrect: 'نام کاربری یا رمز عبور اشتباه می باشد',
    enter_to_app_successfully: 'خوش آمدید',
    edit_profile: 'ویرایش پروفایل',
    notification: 'اطلاعیه ها',
    update_app: 'به روز رسانی نرم افزار',
    info: 'درباره ما',
    change_password: 'تغییر رمز عبور',
    app_name: 'عوارض خودرو',

    pay: 'پرداخت',
    camera_specifications: 'مشخصات دوربین',
    plate_photo: 'تصویر پلاک',
    car_photo: 'تصویر خودرو',
    location_in_map: 'موقعیت مکانی روی نقشه',
    you_have_no_transit: 'عبور و مروری برای این پلاک به ثبت نرسیده است',
    you_have_no_plate: 'پلاکی برای شما به ثبت نرسیده است',
    number_document: 'شماره سند :',
    date_document: 'تاریخ سند :',
    recipt_price: 'مبلغ:',
    total_number: 'تعداد کل:',
    discount: 'تخفیف :',

    taxation: 'مالیات:',
    total_price: 'مبلغ کل:',
    save: 'ذخیره',

    close: 'بستن',
    confirm_password: 'تکرار گذر واژه',

    match_not_password: 'تکرار گذر واژه با گذر واژه مطابقت ندارد',
    are_you_sure_logout_from_app: 'آیا می خواهید از برنامه خارج شوید؟',
    are_you_remove_this_plate: 'آیا می خواهید این پلاک را حذف نمایید؟',
    name: 'نام',
    axis: 'محور',
    latitude: 'عرض جغرافیایی',
    longitude: 'طول جغرافیایی',
    speed_allowed_heavy_vehicle_in_night: 'سرعت مجاز در شب - خودروی سنگین',
    speed_allowed_in_night: 'سرعت مجاز در شب',
    speed_allowed_in_day: 'سرعت مجاز در روز',
    speed_allowed_heavy_vehicle_in_day: 'سرعت مجاز در روز - خودروی سنگین',
    your_sign_is_successfully: 'ثبت نام شما با موفقیت انجام شد',
    your_plate_insert_successfully: 'پلاک شما با موفقیت ثبت شد',
    your_poll_insert_successfully: 'نظرسنجی شما با موفقیت ثبت شد',
    national_code_is_wrong: 'کد ملی وارد شده صحیح نمی باشد',
    something_went_wrong: 'خطایی رخ داده است',
    must_be_at_least: 'باید بیشتر از',
    character: 'حرف',
    was: 'باشد',
    add_plate: 'افزودن پلاک',
    try_again: 'تلاش مجدد',
    logout: 'خروج از حساب کاربری',
    copy_right_text: 'کلیه حقوق برای های وب محفوظ است',

    home: 'خانه',
    stadium_name: 'ورزشگاه بازی',
    add_game: "ایجاد مسابقه"
}